spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
#JWT
jwt:
  header: ${HEADER}
  secret: ${SECRET}
  accessExp: ${ACCESS-EXP}
  refreshExp: ${REFRESH-EXP}
  prefix: ${PREFIX}

---
#OAUTH2
oauth2:
  client:
    registration:
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_SECRET_KEY}
        redirect-uri: ${GOOGLE_REDIRECT_URI}
        scope:
          - profile
          - email
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_SECRET_KEY}
        redirect-uri: ${KAKAO_REDIRECT_URI}
        scope:
          - profile
          - email

---
#S3
aws:
  s3:
    bucket: ${S3_BUCKET}
    access-key: ${S3_ACCESSKEY}
    secret-key: ${S3_SECRET}
  region:
    static: ap-northeast-2